title: Build Log
description: Just a simple build log - to remind me of what I've done
theme: just-the-docs

url: https://just-the-docs.github.io

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
